name: Compile Zato from source code

on:
  push:
    branches:
      - support/3.2
  schedule:
    # Every day at 03:17 AM
    - cron: "17 3 * * *"

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zato-compile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python --version

      - name: Clone and compile
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 3600
          max_attempts: 3
          command: mkdir -p /tmp/src-zato && git clone https://github.com/zatosource/zato && cd ./zato && git checkout support/3.2 && ./code/install.sh && ./code/bin/zato --version && ./code/bin/zato quickstart /tmp/qs-1
